### ISSUE TITLE
MySQL 5.7.6+ and the configuration of ngram Full-Text parser

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/ansible-mattermost#2]
Deployments requiring searching in Chinese, Japanese, and Korean languages require MySQL 5.7.6+ and the configuration of ngram [Full-Text parser](https://dev.mysql.com/doc/refman/5.7/en/fulltext-search-ngram.html). For searching two characters, you will also need to set ft_min_word_len and innodb_ft_min_token_size to 2 and restart MySQL. See [CJK](https://github.com/mattermost/mattermost-server/issues/2033#issuecomment-183872616) discussion for details.

solution, add the following items in `my.cnf`  

```
ngram_token_size=2
ft_min_word_len=2
innodb_ft_min_token_size=2
```

**Comment by qiaofeng1227** [comment]
Done
