### ISSUE TITLE
5.37 has released.(5.37 is not a stable version, is test version)

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/ansible-mattermost#6]
**What type of your feature request?**  

- [ ] Add new features
- [ ] Improve current features

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Describe alternatives you've considered**  

**Additional context**

**Comment by qiaofeng1227** [comment]
https://docs.mattermost.com/upgrade/important-upgrade-notes.html
